### PR TITLE
[DSI-7158] Remove morgan middleware and updated dependencies 

### PR DESCRIPTION
**Pull request by ipredoi**
## Summary
**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7158
## Changes
-Remove unnecessary `morgan` middleware and HTTP request logging to `access.log`
-Updated / removed unused packages to fix 24 vulnerabilities (19 moderate, 5 high): 

- bumped `nodemon` version
- bumped `login.dfe.dao`, `login.dfe.api.auth`, `login.dfe.express-error-handling`, `login.dfe.healthcheck`, `login.dfe.jwt-strategies`, `login.dfe.winston-appinsights` 
- removed unused `login.dfe.request-promise-retry` and `request` libraries from `package.json`

### CODE REVIEW

**Review by JaredAMarsh — APPROVED** [review]
Looks good to me, we never used the `morgan` logs since I've joined for sure, and the request/request-promise-retry packages are unused so all makes sense 👍

**Review by andreaspetridis11 — APPROVED** [review]
Tested successfully on Test environment. Regression test passed

**Review by shravani-kondaparti — COMMENTED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — COMMENTED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — COMMENTED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — COMMENTED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — COMMENTED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — COMMENTED** [review]
Regression tests passed in Test env

**Pull request merged**
